### ISSUE TITLE
need example flow

### ISSUE THREAD

**Issue by ardenking** [justmvg/node-red-contrib-salus-it500#1]
are there a syntax list or examples for using this with node red ?

Im going round in circles trying to get this working

**Comment by justmvg** [comment]
Please use as followed. You can set your salus info on the central node.
![image](https://user-images.githubusercontent.com/36076579/59447094-07e4ec00-8e03-11e9-98a0-aa63db1476c8.png)

Please let me know if you need any assistance.

**Comment by mindvisionro** [comment]
Do you know if this working with it600?

**Comment by justmvg** [comment]
> Do you know if this working with it600?

This particular module won't work for the it600 as it is using a different endpoint. I'm pretty sure it would be possible to create a module for the it600 similar as the it500. However, I do not have this device so unfortunately I won't be able to create it.

**Comment by mindvisionro** [comment]
The endpoint for it600 is https://eu.salusconnect.io/dashboard, you can use the demo account or my account to take a look if you want and have time. I want to integrate this to Home Assistant but salus is not providing any kind of api :(.

**Comment by potential-power** [comment]
Is there an issue with the node-red node. It says it cant get a token or ID. It seems the https://salus-it500.com/ url is not reachable any more. Any fix in place for this. Thanks Laurie
